[package]
name = "standard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked_list_allocator = {version="0.9.1", features =["default","alloc_ref","use_spin"]}

