[target.'cfg(target_os = "none")']
runner="./runner.sh"
rustflags = [
	"-C", "link-arg=--image-base=0xffff800000000000",
]

[alias]
kbuild = "build -Zbuild-std"
kimage = "run -Zbuild-std --no-run"
krun = "run -Zbuild-std"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-custom.json"
rustdocflags = ["--document-private-items"]
