[target.'cfg(target_os = "none")']
runner = "cargo run --package simple_boot --"

[alias]
kbuild = "build --target x86_64-custom.json -Z build-std"
kimage = "run --target x86_64-custom.json -Z build-std --no-run"
krun = "run --target x86_64-custom.json -Z build-std"
