[target.'cfg(target_os = "none")']
runner="./runner.sh"
# runner = "cargo run --package simple_boot --"

[alias]
kbuild = "build -Zbuild-std"
kimage = "run -Zbuild-std --no-run"
krun = "run -Zbuild-std"

[unstable]
build-std = ["core", "compiler_builtins","alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-custom.json"