[workspace]


members = [
  "standard",
  "shell",
  "fibonachi",
  "black_and_solve",
  "cowsay",
  "cat",
  "echo",
  "touch",
  "ls",
  "hangman",
  "divide",
  "null_ptr",
  "loop",
  "pi",
  "count",
  "rmdir",
  "rm",
  "cp",
  "mkdir",
  "mv",
]
